version: '3.8'

services:
  algafood_postgres:
    container_name: container_algafood_postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: db_algafood
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - algafood-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://algafood_postgres:5432/db_algafood
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - algafood_postgres
    networks:
      - algafood-network

networks:
  algafood-network:
